import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Header from "./components/header/Header";
import "./globals.css";
import { MainProvider } from "./context/MainContext";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Golobe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <MainProvider>
          <Header />
          {children}
        </MainProvider>
      </body>
    </html>
  );
}
